FROM 172.16.3.204:5000/lab/offical-instance:py3common

RUN pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl
RUN pip install torchvision

RUN pip install visdom