FROM 172.16.3.204:5000/lab/offical-instance:py3common


ADD torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl /tmp/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl
RUN pip install /tmp/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl
RUN pip install torchvision

RUN pip install visdom

RUN rm /tmp/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl