#!/bin/sh

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
autocutsel -fork
vncconfig -iconic &

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &



{
    "id": "gpu-docker-test",
    "cmd": "echo $HOST && while [ true ]; do nvidia-smi; sleep 60; done",
     "acceptedResourceRoles":["slave_public", "*"],
    "cpus": 0.1,
    "mem": 129.0,
    "gpus": 1,
    "instances": 1,
    "container": {
        "type": "MESOS",
        "mesos": {
            "image": "lab/nvidia/cuda"
        }
    }
}
