FROM kaixhin/cuda-torch:latest
MAINTAINER heyflypig <heyflypig@gmail.com>

RUN luarocks install async
RUN luarocks install display

COPY run_host_train.sh /root/run_host_train.sh

RUN chmod +x /root/run_host_train.sh