# Start with CUDA Theano base image
FROM 172.16.3.204:5000/lab/offical-instance:theano
MAINTAINER Kai Arulkumaran <design@kaixhin.com>

# Install bleeding-edge Lasagne
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
