周末两天计划

1.周五7点-周六早上9点，备份数据。
2.周六早上9点到下午两点 搭建ceph集群，rbd块。
3.下午2点到第二天早上，回迁数据
4.周六下午搭建zabbix监控,观察rbd性能，如果不理想就回退
5.周日早上整合云盘，测试计算节点挂载rbd，能被mesos作为PV

风险                          解决方案
  
1.rbd不能抗住小文件压力                  回退
2.nfs挂载rbd设备，云盘不能识别          选用别的文件共享方式
3.mesos 的volume drive 不能挂载ceph     用nfs

sudo apt-get remove linux-image-4.4.0-75-generic linux-headers-4.4.0-75-generic
